In [1]:
import pandas as pd

In [2]:
#set dataframes for cleanup
characters = pd.read_csv("data/simpsons_characters_edit.csv")
lines = pd.read_csv("data/simpsons_script_lines.csv", error_bad_lines=False)
episodes = pd.read_csv("data/simpsons_episodes.csv")

b'Skipping line 8084: expected 13 fields, saw 20\nSkipping line 52607: expected 13 fields, saw 21\nSkipping line 59910: expected 13 fields, saw 21\n'
b'Skipping line 71801: expected 13 fields, saw 20\nSkipping line 73539: expected 13 fields, saw 21\nSkipping line 77230: expected 13 fields, saw 21\nSkipping line 78953: expected 13 fields, saw 21\nSkipping line 81138: expected 13 fields, saw 20\nSkipping line 86746: expected 13 fields, saw 22\nSkipping line 101154: expected 13 fields, saw 21\nSkipping line 115438: expected 13 fields, saw 20\nSkipping line 117573: expected 13 fields, saw 22\nSkipping line 130610: expected 13 fields, saw 22\n'
b'Skipping line 152970: expected 13 fields, saw 22\nSkipping line 153017: expected 13 fields, saw 20\nSkipping line 153018: expected 13 fields, saw 30\nSkipping line 154080: expected 13 fields, saw 20\nSkipping line 154082: expected 13 fields, saw 20\nSkipping line 154084: expected 13 fields, saw 20\nSkipping line 154086: expected 13 fields, saw 20\nSkipping line 154089: expected 13 fields, saw 23\nSkipping line 154165: expected 13 fields, saw 21\nSkipping line 156872: expected 13 fields, saw 20\n'
/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
#including columns needed for analysis
episodes = episodes[["id", "season", "number_in_season", "number_in_series", "title", "imdb_rating", "image_url"]]
episodes = episodes[episodes.season != 28]

In [4]:
null_columns=episodes.columns[episodes.isnull().any()]
episodes[null_columns].isnull().sum()

#search for null in columns
print(episodes[episodes.isnull().any(axis=1)][null_columns])
#clear NAN columns
episodes.iloc[189,6] = ""
episodes.count()

    image_url
189       NaN

id                  596
season              596
number_in_season    596
number_in_series    596
title               596
imdb_rating         596
image_url           596
dtype: int64

In [5]:
#rename columns in episodes
episodes = episodes.rename(columns={"id": "episode_id", "number_in_season": "season_episode_no", "number_in_series": "episode_overall_no"})
episodes.sort_values(by=['episode_id'], inplace=True)
episodes = episodes.set_index("episode_id")

In [6]:
#set columns and rows for characters
characters = characters.rename(columns={"id":"char_id"})
characters.sort_values(by=["char_id"], inplace=True)
characters = characters.set_index("char_id")
characters

,name,normalized_name,gender,Simpson_fam
char_id,,,,
1,Marge Simpson,marge simpson,f,True
2,Homer Simpson,homer simpson,m,True
3,Seymour Skinner,seymour skinner,m,False
4,JANEY,janey,f,False
5,Todd Flanders,todd flanders,m,False
6,Dewey Largo,dewey largo,m,False
7,Children,children,u,False
8,Bart Simpson,bart simpson,m,True
9,Lisa Simpson,lisa simpson,f,True
10,Patty Bouvier,patty bouvier,f,False
11,Ned Flanders,ned flanders,m,False
12,Mechanical Santa,mechanical santa,m,False
13,Tattoo Man,tattoo man,m,False
14,Waylon Smithers,waylon smithers,m,False
15,C. Montgomery Burns,c montgomery burns,m,False
16,DOCTOR ZITSOFSKY,doctor zitsofsky,u,False
17,Moe Szyslak,moe szyslak,m,False
18,Barney Gumble,barney gumble,m,False
19,Interviewer,interviewer,m,False
20,Students,students,u,False
21,Teacher,teacher,m,False
22,Selma Bouvier,selma bouvier,f,False
23,Voice,voice,m,False
24,Little Boy,little boy,m,False
25,Milhouse Van Houten,milhouse van houten,m,False
26,Lewis Clark,lewis clark,m,False
27,Little Girl,little girl,f,False
28,Clerk,clerk,m,False
29,Bubbles,bubbles,u,False
30,Moldy,moldy,u,False
...,...,...,...,...
6720,ELON MUSK,elon musk,m,False
6721,ELON,elon,m,False
6722,IMAGINER,imaginer,u,False
6723,YOUNG JEWISH MAN,young jewish man,m,False
6724,YOUNG MOLEMAN,young moleman,m,False
6725,TUSCALOOSA PEOPLE,tuscaloosa people,u,False
6726,PHARRELL WILLIAMS,pharrell williams,m,False
6727,PRIDESTERS,pridesters,u,False
6728,ALBERT,albert,m,False
6729,LANEY FONTAINE,laney fontaine,u,False
6730,LADY DUFF,lady duff,f,False
6731,BOOK CLUB MEMBER,book club member,u,False
6732,OTHER BOOK CLUB MEMBER,other book club member,u,False
6733,HEAD INSPECTOR,head inspector,u,False
6734,SIKH CAB DRIVER,sikh cab driver,u,False
6735,JIM IGNATOWSKI,jim ignatowski,u,False
6736,CHAPIN-LIKE SINGER,chapin-like singer,u,False
6737,HARRY CHAPIN-TYPE SINGER,harry chapin-type singer,m,False
6738,CABBIES,cabbies,u,False
6739,SMILE,smile,u,False
6740,KEMI,kemi,u,False
6741,PEDICAB DRIVER,pedicab driver,u,False
6742,SMITHERS' THOUGHTS,smithers thoughts,m,False
6743,AGED MOE,aged moe,m,False
6744,RICHARD BRANSON,richard branson,m,False
6745,CHURCH GROUP,church group,u,False
6746,COCKTAIL WAITRESSES,cocktail waitresses,f,False
6747,SECURITY THUG #1,security thug 1,u,False
6748,SECURITY THUG #2,security thug 2,u,False
6749,LATINO WORKERS,latino workers,u,False

In [7]:
#lots of internal dialogue in simpsons, deleting for actual lines
lines = lines.loc[lines["speaking_line"]==True]
lines = lines[["id", "episode_id", "number", "character_id", "normalized_text", "word_count"]]
lines = lines.rename(columns={"id":"line_id"})
type(lines)

pandas.core.frame.DataFrame

In [8]:
#clean up nan rows, and sort and reindex
lines = lines.dropna()
lines.sort_values(by=["line_id"], inplace=True)
lines = lines.set_index("line_id")
type(lines)

pandas.core.frame.DataFrame

In [9]:
lines.count()

episode_id         109012
number             109012
character_id       109012
normalized_text    109012
word_count         109012
dtype: int64

In [10]:
#export csv and json files for future import
episodes.to_csv("data/episodes_final.csv")
lines.to_csv("data/lines_final.csv")
characters.to_csv("data/characters_final.csv")
episodes.to_json("data/episodes_final.json")
lines.to_json("data/lines_final.json")
characters.to_json("data/characters_final.json")